"""country_id field added

Revision ID: 83ade7a29406
Revises: 4b9bfeb5e4b8
Create Date: 2024-11-18 10:38:44.980764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ade7a29406'
down_revision: Union[str, None] = '4b9bfeb5e4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('countries_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'states', 'countries', ['countries_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.drop_column('states', 'countries_id')
    # ### end Alembic commands ###
